---
- name: 'Priority: Critical'
  color: 'B60205'
- name: 'Priority: Low'
  color: '0E8A16'
- name: 'Priority: Medium'
  color: 'FBCA04'
- name: 'Status: Fixed'
  color: '0E8A16'
- name: 'Status: Pending'
  color: 'FBCA04'
- name: 'Status: Abandoned'
  color: '000000'
- name: 'Type: Breaking'
  color: 'FF0000'
- name: 'Type: Bug'
  color: 'B60205'
- name: 'Type: Enhancement'
  color: '1D76DB'
- name: 'Type: Duplicate'
  color: 'FBCA04'
- name: 'Type: Question'
  color: '5319E7'
- name: 'Type: Rejected'
  color: 'FBCA04'
- name: 'Type: Documentation'
  color: '1D76DB'
