dist: trusty
group: travis_latest
#language: ruby
#branches:
#  except:
#  - "/^v\\d/"
#cache:
#  directories:
#  - vendor/bundle
script:
- |
  if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
    echo master
  elif [[ "$TRAVIS_TAG" =~ ^v\\d ]]; then
    echo tag
  fi
