env:
  VAULT_ADDR: 'https://vault.ghn.me:8200'
  VAULT_VERSION: '1.1.2'
install:
  - wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
  - wget -O - https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS | grep linux_amd64 | sha256sum -c
  - unzip vault_${VAULT_VERSION}_linux_amd64.zip
  - mv vault ~/bin/
script:
  - echo 'Using VAULT'
  - export VAULT_SECRET_ID="$(vault write -field=secret_id -f auth/approle/role/travis_amis/secret-id)"
  - export VAULT_TOKEN="$(vault write -field=token auth/approle/login role_id=${VAULT_ROLE_ID} secret_id=${VAULT_SECRET_ID})"
  - 'echo "Testing is: $(vault kv get -field=test vgh/travis/amis)"'
  - echo 'Using CURL'
  - 'export VAULT_SECRET_ID="$(curl --header "X-Vault-Token: ${VAULT_TOKEN}" --request POST ${VAULT_ADDR}/v1/auth/approle/role/travis_amis/secret-id | jq -r .data.secret_id)"'
  - export VAULT_TOKEN="$(curl --request POST --data \"{\"role_id\":\"${VAULT_ROLE_ID}\",\"secret_id\":\"${VAULT_SECRET_ID}\"}\" ${VAULT_ADDR}/v1/auth/approle/login | jq -r .auth.client_token)"
  - 'echo "Testing is: $(curl --header "X-Vault-Token: ${VAULT_TOKEN}" ${VAULT_ADDR}/v1/vgh/data/travis/amis | jq -r .data.data.test)"'
