dist: trusty
group: travis_latest
#language: ruby
#branches:
#  except:
#  - "/^v\\d/"
#cache:
#  directories:
#  - vendor/bundle
jobs:
  include:
    - stage: stage1
      env:
        PACKER_VERSION: '1.2.5'
        SC_VERSION: 'stable' # or "v0.4.7", or "latest"
      script: echo 'Stage 1'; env
    - stage: stage2
      script: - |
                if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
                  . shlib/docker.sh && run_push && run_post_push
                elif [[ "$TRAVIS_TAG"  =~ ^v\\d ]]; then
                  . shlib/docker.sh && run_push && run_post_push
                fi
