name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ami:
          - name: testami1
            profile: testprofile1
          - name: testami2
            profile: testprofile2
    steps:
    - uses: actions/checkout@v1
    - name: test
      run: echo "Running ${AWS_NAME} with ${AWS_PROFILE}"
      env:
        AWS_NAME: ${{ matrix.ami.name }}
        AWS_PROFILE: ${{ matrix.ami.profile }}
      if: matrix.ami.name != 'testami1'
    - run: git clone https://github.com/vghn/ansible ../ansible
    - name: Install Packer
      run: |
            wget -q "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
            wget -qO - "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS" | grep linux_amd64 | sha256sum -c
            sudo unzip -d /usr/local/bin/ "packer_${PACKER_VERSION}_linux_amd64.zip"
            packer version
    - name: Install Vault
      run: |
            wget -q "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
            wget -qO - "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS" | grep linux_amd64 | sha256sum -c
            sudo unzip -d /usr/local/bin/ "vault_${VAULT_VERSION}_linux_amd64.zip"
            vault version
    # - name: Set up Python
    #   uses: actions/setup-python@v1
    # - name: Install dependencies
    #   run: |
    #     python3 -m pip install --upgrade pip ansible hvac pycrypto aws-amicleaner future
    # - run: ansible --version
    # - run: amicleaner --version
    # - name: Run a one-line script
    #   run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
