name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ami:
          - name: testami1
            profile: testprofile1
          - name: testami2
            profile: testprofile2
    steps:
    # - uses: actions/checkout@v1
    - name: test
      run: echo "Running ${{ matrix.ami.name }} with ${AWS_PROFILE}"
      with:
        AWS_PROFILE: ${{ matrix.ami.profile }}
    # - name: Set up Python
    #   uses: actions/setup-python@v1
    # - name: Install dependencies
    #   run: |
    #     python3 -m pip install --upgrade pip ansible hvac pycrypto aws-amicleaner future
    # - run: ansible --version
    # - run: amicleaner --version
    # - name: Run a one-line script
    #   run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
