name: Labels

on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml

jobs:
  labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Label actions
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
