name: Release

on: [push]

jobs:
  publish:
    name: Publish collection to Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Publish collection
        uses: docker://ghcr.io/artis3n/ansible_galaxy_collection@latest
        with:
          api_key: '${{ secrets.ANSIBLE_GALAXY_API_KEY }}'
          galaxy_version: '${{ env.RELEASE_VERSION }}'
