name: Release

on:
  push:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - runs: printenv
    - name: Generate Changelog
      run: "docker run --rm -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/usr/local/src/your-app ferrarimarco/github-changelog-generator --user vladgh --project test --bug-labels 'Type: Bug' --enhancement-labels 'Type: Enhancement' --future-release $(git describe --always --tags)"
    - run: cat CHANGELOG.md
    - run: |
        git config user.email "vlad@ghn.me"
        git config user.name "CI"
        git add CHANGELOG.md && git commit -m 'Update changelog' && git push
