name: Release

on:
  pull_request:
    types: [closed]

  issues:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Break the semantic version into components
      run: |
        semver="$(git describe --always --tags)"
        semver="${semver#v}" # Remove the 'v' prefix
        semver="${semver%%-*}" # Remove the commit number
        IFS="." read -r -a semver <<< "$semver" # Create an array with version numbers
        echo ::set-env name=MAJOR::${semver[0]}
        echo ::set-env name=MINOR::${semver[1]}
        echo ::set-env name=PATCH::${semver[2]}
    - name: Increment major version
      run: echo ::set-env name=MAJOR::$((MAJOR+1))
      if: "contains(github.event.issue.labels.*.name, 'Backwards incompatible')"
    - name: Increment minor version
      run: echo ::set-env name=MINOR::$((MINOR+1))
      if: "contains(github.event.issue.labels.*.name, 'Type: Enhancement')"
    - name: Increment patch version
      run: echo ::set-env name=PATCH::$((PATCH+1))
      if: "contains(github.event.issue.labels.*.name, 'Type: Bug')"
    - name: Generate Changelog
      run: docker run --rm -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/usr/local/src/your-app ferrarimarco/github-changelog-generator --user "$(dirname $GITHUB_REPOSITORY)" --project "$(basename $GITHUB_REPOSITORY)" --future-release "v${MAJOR}.${MINOR}.${PATCH}"
    - name: Configure git
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
    - name: Commit CHANGELOG.md
      run: |
        if ! git diff --quiet HEAD; then
          git add CHANGELOG.md && git commit -m 'Update changelog'
          git push origin master
        fi
    - name: Tag release
      run: |
        git tag "v${MAJOR}.${MINOR}.${PATCH}" --message "Release v${MAJOR}.${MINOR}.${PATCH}"
        git push --follow-tags
