name: Release

on:
  pull_request:
    types: [closed]

  issues:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest
    - name: Break the semantic version into components
      run: |
        tag="$(git describe --always --tags)"
        semver="${tag#v}" # Remove the 'v' prefix
        semver="${semver%%-*}" # Remove the commit number
        IFS="." read -r -a semver <<< "$semver" # Create an array with version numbers
        echo ::set-env name=MAJOR::${semver[0]}
        echo ::set-env name=MINOR::${semver[1]}
        echo ::set-env name=PATCH::${semver[2]}
    - name: Test
      run: echo 'exists'
      if: "contains(github.event.issue.labels.*.name, 'Type: Bug')"
    - name: Generate Changelog
      run: |
        docker run --rm -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/usr/local/src/your-app ferrarimarco/github-changelog-generator --user "$(dirname $GITHUB_REPOSITORY)" --project "$(basename $GITHUB_REPOSITORY)" --future-release $(git describe --always --tags)
    - run: cat CHANGELOG.md
    - run: |
        git config user.name "GitHub Release Bot"
        git config user.email "vladgh@users.noreply.github.com"
        git add CHANGELOG.md && git commit -m 'Update changelog' && git push origin master
