name: Release

on:
  pull_request:
    types: [closed]

  issues:
    types: [closed]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: printenv
    - name: Generate Changelog
      run: |
        docker run --rm -e CHANGELOG_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v $(pwd):/usr/local/src/your-app ferrarimarco/github-changelog-generator --user "$(dirname $GITHUB_REPOSITORY)" --project "$(basename $GITHUB_REPOSITORY)" --future-release $(git describe --always --tags)
    - run: cat CHANGELOG.md
    - run: |
        git config user.email "${{ secrets.GITHUB_ACTOR }}"
        git add CHANGELOG.md && git commit -m 'Update changelog' && git push origin master
